### ISSUE TITLE
"Something went wrong" frequently displayed by Spritradar

### ISSUE THREAD

**Issue by Eierkopp** [xXSparkeyy/harbour-spritradar#12]
Sometimes tankerkoenig.de doesn't deliver a "brand" with its response such that computation of stationName raises an exception. In that case only "Something went wrong" is displayed by Spritradar. Below please find is a possible fix.

    diff --git a/qml/pages/Plugin/TankerKoenig.qml b/qml/pages/Plugin/TankerKoenig.qml
    index a810798..6a39f7d 100644
    --- a/qml/pages/Plugin/TankerKoenig.qml
    +++ b/qml/pages/Plugin/TankerKoenig.qml
    @@ -74,9 +74,10 @@ Plugin {
                         for( var i = 0; i < x.length; i++ ) {
                             var o = x[i]
                             if( contentItem.hideClosed && !o.isOpen ) continue
    +                        var brand = (o.brand == null) ? "" : o.brand
                             var itm = {
                                 "stationID": o.id,
    -                            "stationName": (o.name.toLowerCase().substring(0, o.brand.length)==o.brand.toLowerCase()?"":o.brand+" ")+o.name,
    +                            "stationName": (o.name.toLowerCase().substring(0, brand.length)==brand.toLowerCase()?"":brand+" ")+o.name,
                                 "stationPrice": o.price,
                                 "stationAdress": capitalizeString(o.street) + (typeof(o.houseNumber) == "object" ? "" : " " + o.houseNumber) + ", " + o.postCode + " " + capitalizeString(o.place),
                                 "stationDistance": o.dist*1000,

**Comment by xXSparkeyy** [comment]
Never experienced that, but seems legit. Many thanks for the fix, but could u please open a pull request or send me the modified file?
