### ISSUE TITLE
Spanish Database?

### ISSUE THREAD

**Issue by PaskoMoto** [xXSparkeyy/harbour-spritradar#14]
Hi and thank you for this useful app.

As of April the 8th 2017 the app stopped working with Spanish database. It still works with German and Italian databases.
Previously I had also noticed that the native SailfishOS maps app link is broken because the native maps app is no longer available to JollaC devices.
I'm in a JollaC with version 2.1.0.11
Thanks in advance and keep the good work.
Regards.

**Comment by xXSparkeyy** [comment]
The web hoster eventually blocked my account, moved everything to a new one everything should be back by tomorrow. I think there is nothing i can do about that broken map thing.

**Comment by PaskoMoto** [comment]
Hi.
Thank you for your answer. Will check it tomorrow.
Regards.

**Comment by PaskoMoto** [comment]
Hi.

Unfortunately the app still doesn't work. I tried with this url with my browser and all I get is an empty list:
http://harbour-spritradar.w4f.eu/es/?get=stations&lat=40.500471&lng=-3.667394199999999&radius=9

Regards.

**Comment by xXSparkeyy** [comment]
U checked too early, it works as it should.

**Comment by PaskoMoto** [comment]
Ok.
Now it works. 
Thank you very much.

**Comment by PaskoMoto** [comment]
Hello again.
Unfortunately it is failing again......
Regards.

**Comment by xXSparkeyy** [comment]
The database was deleted somehow, it's fixed now and should work fine (again).

**Comment by PaskoMoto** [comment]
Hi.
It works fine now.
Thanks (again). :)
