### ISSUE TITLE
Options in pulley menu on Favourites page not selectable

### ISSUE THREAD

**Issue by Pohli** [xXSparkeyy/harbour-spritradar#18]
See title. Both options are greyed out.

Jolla Phone with SFOS 3.0.0.8, Spritradar 2.8

**Comment by xXSparkeyy** [comment]
If you use spritpreisrechner.at, this is intentional because the Api doesn't(/hadn't) have a backend for getting Information on stations directly.

**Comment by Pohli** [comment]
I'm using Tankerkönig.
Issue seems to only occur if Favourites page is set as First Page.

**Comment by xXSparkeyy** [comment]
Okay yes it is an Copy&Paste bug :D I will fix this and add your other recommended feature. But this will take some time and You could (forst of all update to 2.9) and remove the "enabled: (...)" line of the MenuItem from Favs.qml (using nano i.e. ) veröffentlichen

**Comment by Pohli** [comment]
Will version 2.9 be released at Jolla Store soon?

**Comment by xXSparkeyy** [comment]
Feature available in Current version on OpenRepos.net.
If the version on OpenRepos.net produces no Bugs it will be uploaded to Jolla Store.

**Comment by Pohli** [comment]
Updated from Jolla Store and works fine now. Thank you very much!
