### ISSUE TITLE
Custom names for favourites

### ISSUE THREAD

**Issue by Pohli** [xXSparkeyy/harbour-spritradar#19]
The petrol station names from the database are often very similar and then it's not possible to differ the items from each other at a quick glance (have to call details page first). So an option to rename favourites would be nice.

**Comment by xXSparkeyy** [comment]
As a hacky solution, you could edit the ~/.config/harbour-spritradar/harbour-spritradar.conf and rename Favorites/stationX={some-id}|{name}
