### ISSUE TITLE
China oil price  API

### ISSUE THREAD

**Issue by dashinfantry** [xXSparkeyy/harbour-spritradar#25]
https://translate.googleusercontent.com/translate_c?depth=1&nv=1&rurl=translate.google.com.hk&sl=auto&sp=nmt4&tl=en&u=https://www.avatardata.cn/Docs/Api/a77e2154-2789-43a2-a30e-aa34d95df26d&xid=25657,15700022,15700186,15700191,15700256,15700259,15700262,15700265&usg=ALkJrhgNs3KWI5G0FdNjyNASPwnOAdfNVg

**Comment by xXSparkeyy** [comment]
Insufficent Information
