### ISSUE TITLE
[Feature Request] Export favorites

### ISSUE THREAD

**Issue by HansRoulade** [xXSparkeyy/harbour-spritradar#30]
Would be nice to be able to export favorites as XML or whatever, for the purpose of backups and re-importing on other devices.

**Comment by xXSparkeyy** [comment]
Favorites are stored in ~/.conf/harbour-spritradar/harbour-spritradar.conf, copying this file should suffice as a way to backup and transfer.

**Comment by HansRoulade** [comment]
Good to know, thanks!
