### ISSUE TITLE
[ISSUE] GeoportalGasolineras.es API seems to stop working in Spritradar

### ISSUE THREAD

**Issue by ferlanero** [xXSparkeyy/harbour-spritradar#32]
As a heavy user of this fantastic app I have noticed that since a week ago, Spritradar can't retrieve information from [geoportalgasolineras.es](https://geoportalgasolineras.es/#/Inicio) as they did before. In screenshots you can see my configuration:

![photo_2020-01-04_12-07-59 (2)](https://user-images.githubusercontent.com/1192395/71764881-22d99380-2eee-11ea-81e2-eeb43c81c674.jpg)

And the error SpritRadar bring back now:

![photo_2020-01-04_12-07-59](https://user-images.githubusercontent.com/1192395/71764911-68965c00-2eee-11ea-87ca-e7760aad9465.jpg)

I have tested versions from Jolla Store & Operepos.net and both have the same issue. It will be possible to fix the access to geoportalgasolineras.es in Sritradar, please? This application is tons useful!

**Comment by xXSparkeyy** [comment]
New Version on Openrepos.net right now, Store version in QA.
