### ISSUE TITLE
Centre page titles

### ISSUE THREAD

**Issue by Pohli** [xXSparkeyy/harbour-spritradar#34]
What I've always found confusing is that the page titles (Favourites, Search, Results) are aligned to the right edge just next to the swipe left button (that blurred dot in the upper right corner, don't know the terminology). It makes you assume that you'll get to that page if you swipe left instead of recognising it as a page title.

Jolla Phone with SFOS 3.0.1.11 and SpritRadar 2.11

**Comment by xXSparkeyy** [comment]
Hi, thanks for the feedback. According to what I've seen, this seems so be the standard (e.g. E-Mail or Settings app), although understanding your point, I think it would look off, considering the whole System. 
The dot is called PageIndicator and as in the name, and should just indicate that there is a Page in its direction.
