### ISSUE TITLE
project dead?

### ISSUE THREAD

**Issue by Armadill0** [xXSparkeyy/harbour-spritradar#5]
Hey,

as there wasn't a new version since months, although there's new code which could be published in the store, my question: Is the project dead?

Before I start to fork the project and publish this, I wanted to ask you if the development will go on in the future.

Best regards

**Comment by xXSparkeyy** [comment]
Hi,

Thanks for the reminder, after the SDK-Udate I couldn't deploy anymore and forgot about it, but now I fixed it and will update the version.

**Comment by Armadill0** [comment]
Great to hear! :smile:
