### ISSUE TITLE
Fuel names

### ISSUE THREAD

**Issue by ghost** [xXSparkeyy/harbour-spritradar#6]
Great app, thanks for making apps for SFOS!

I find a bit difficult to guess what fuel is each of the three letters acronym, could be possible to use complete names?

Thanks!!

**Comment by xXSparkeyy** [comment]
Yes, I will include this in a Spain translation. If ur from Spain, would u make the translation?

**Comment by ghost** [comment]
I'll do it! :)

**Comment by xXSparkeyy** [comment]
Fixed this and added the [Translation File](https://github.com/xXSparkeyy/harbour-spritradar/blob/master/translations/harbour-spritradar-es.ts), would be kind of you to translate it :)
